on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to echo on each push
    steps:
    - name: Echo (on each push)
      id: run
      uses: bioimagesuiteweb/bisweb/actions/push@devel
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Logfile
      run: echo "${{ steps.run.outputs.logfile}}"
    