on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to perform regression tests for bisweb
    steps:
    - name: Test on push
      id: run
      uses: bioimagesuiteweb/experiments/actions/push@master
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Logfile
      run: echo "${{ steps.run.outputs.logfile}}"
    