on: [push]

jobs:
  hosted_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    name: bisweb-test
    steps:
    - name: Global Prereqs
      run: |
        echo "----------------------------------------------------"
        echo "cmake = `which nmake` `cmake --version`"
        echo "nmake = `which nmake`"
        echo "git = `which git` `git --version`"
        echo "python = `which python` `python --version`"
        echo "node = `which node` `node --version`"
        echo "----------------------------------------------------"
        cd $HOME
        pwd
        dir
      shell: bash
    - name: NPM Install
      run : |
        choco install visualstudio2017buildtools  
        npm install -g gulp mocha rimraf
      shell: bash
    - name: "VS 2017"
      run: |
        cd c:\"Program Files (x86)"
        dir
        cd "Microsoft Visual Studio"
        dir
        cd 2017
        dir
        cd BuildTools
        dir
        cd VC
        dir
        cd Auxiliary
        dir
        cd Build
        dir
        vcvars64.bat
        where nmake.exe
      shell: cmd
