on: [push]

jobs:
  hosted_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    name: bisweb-test
    steps:
    - name: Global Prereqs
      run: |
        where git.exe
        where nmake.exe
        where npm
        echo %PATH%
        python --version
        git --version
        node --version
        cmake --version
        cd C:\"Program Files"\Git\bin\
        dir
        bash.exe --version
      shell: cmd
    - name: NPM Install
      run : |
        npm install -g gulp mocha rimraf
      shell: cmd
    - name: "VS 2017"
      run: |
        choco install visualstudio2017buildtools
        cd c:\"Program Files (x86)"
        dir
        cd "Microsoft Visual Studio"
        dir
        cd 2017
        dir
        cd BuildTools
        dir
        cd VC
        dir
        cd Auxiliary
        dir
        cd Build
        dir
        vcvars64.bat
        where nmake.exe
      shell: cmd
