on: [push]

jobs:
  hosted_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    name: bisweb-test
    steps:
    - name: Environment Test
      run: |
        echo "----------------------------------------------------"
        echo "cmake = `which nmake` `cmake --version`"
        echo "nmake = `which nmake`"
        echo "git = `which git` `git --version`"
        echo "python = `which python` `python --version`"
        echo "node = `which node` `node --version`"
        echo "----------------------------------------------------"
        pwd
        cd ../..
        ls -lRt
      shell: bash
    - name: Temp Directory
      run: |
        mkdir /d/tmp
        cd /d/tmp
        pwd
        ls -lRt /d/tmp
      shell: bash
    - name: Clone
      run: |
        mkdir -p /d/tmp/bisweb/src
        cd /d/tmp/bisweb
        git clone https://github.com/bioimagesuiteweb/bisweb src
        cd src
        git checkout devel
        git pull
        cp npm-shrinkwrap-orig.json npm-shrinkwrap.json
      shell: bash
    - name: Clone Plugin
      run: |
        cd /d/tmp/bisweb
        mkdir -p /d/tmp/bisweb/gpl
        git clone https://github.com/bioimagesuiteweb/gplcppcode gpl
        cd gpl
        git pull
      shell: bash
    - name: Global Prereq
      run : |
        npm install -g mocha rimraf2
        python -m pip install --upgrade pip setuptools
        python -m pip install numpy nibabel
      shell: bash
    - name : Python Prereqs
      run: |
        cd /d/tmp/bisweb/src
        python -m pip install --user -r biswebpython/config/requirements.txt
      shell: bash
    - name : JS Prereqs
      run: |
        cd /d/tmp/bisweb/src
        npm install -d
        node config/createbuild.js
        chmod +x /d/tmp/bisweb/src/compiletools/*.sh    
      shell: bash
    - name: "VS 2017"
      run: |
        choco install visualstudio2017buildtools
        choco install visualstudio2017-workload-vctools
      shell: cmd
    - name "Build"
        c:
        cd "\Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\VC\Auxiliary\Build
        dir
        vcvars64.bat
        where nmakee.exe
        d:
        cd \tmp\bisweb\src\build
        echo "-------------------------------------------------"
        echo "Beginning build"
        echo "-------------------------------------------------"
        bash d:\tmp\bisweb\src\compiletools\fullbuild.sh
        cd \tmp\bisweb\src
        shell: cmd
    - name : Test
      run : bash d:\tmp\bisweb\src\actions\hosted\dockeractiontest.sh /d/tmp 1 1000
      id: run    
      shell: bash
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
      shell: bash
    - name: Store Results
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: /d/tmp/bisweb/src/build/output/logs
    - name: Store Libraries
      uses: actions/upload-artifact@v1
      with:
        name: libraries
        path: /d/tmp/bisweb/src/build/output/libraries
